### ISSUE TITLE
A big part of the window isn't rendered on startup

### ISSUE THREAD

**Issue by sunshinehunter** [XNBlank/discord-linux#11]
Everytime I start Discord Linux in Arch Linx, XFCE 4.12, a big part of the window isn't rendered, as seen here: https://gyazo.com/a01feaf0b3cafaed576520aad52fd2c6 Resizing the window resolves it.

**Comment by jacobmischka** [comment]
Does this happen with other electron apps? Atom and Slack are the most notable examples.

**Comment by sunshinehunter** [comment]
I tried Slack, it starts without a problem

**Comment by XNBlank** [comment]
Not sure why it would do that, and I'm unable to reproduce this.

**Comment by jacobmischka** [comment]
Occasionally when I open electron apps part of the window is white for a few seconds, but once it finishes loading it fills in like normal. It's odd that yours stays that way. Are you using PRIME by chance?

**Comment by sunshinehunter** [comment]
No, I only have Intel Graphics on a notebook

**Comment by sunshinehunter** [comment]
This is the log on startup when launching it from the command line: http://pastebin.com/MZKz780d

**Comment by Quantum-cross** [comment]
> Are you using PRIME by chance? 

@jacobmischka 
I'm using nvidia with bumblebee and I'm getting other weird glitchy graphics. Is this a known issue? I tried running discord-linux with primusrun, optirun, and intel drivers and I'm getting the same result.

EDIT: Nevermind, I found the bug reports under Atom to change the intel driver to uxa rather than sna.
Link for anyone else who has this problem: atom/atom#10714, atom/atom#10829, https://wiki.archlinux.org/index.php/Intel_graphics#SNA_issues

Also even if you're not using prime, this fix might be relevant to you @SunshineHunter, it seems like a general intel graphics problem.

**Comment by jacobmischka** [comment]
[Yeah, it's a known issue with PRIME in general](https://wiki.archlinux.org/index.php/PRIME#When_an_application_is_rendered_with_the_discrete_card.2C_it_only_renders_a_black_screen), but I don't know about bumblebee. Probably unrelated. 

Yeah the problem is with electron, there's no way anything that this package is doing would cause it.

**Comment by gourdcaptain** [comment]
I'm having this same issue on a netbook using the r600 MESA drivers for my integrated Radeon GPU. Any suggestions? (Already had to install the infinality packages to avoid a black screen, works fine on my main system using the intel drivers).

EDIT: Changing the window size seems to fix the problem if I do it after it loads.

**Comment by jacobmischka** [comment]
My suggestion is to yeah, just resize the window. You can try this if you want, it should just force a resize event. If it helps we can probably just do that onload to workaround this problem. https://github.com/jacobmischka/discord-linux/tree/force-resize

For the record, I have no idea if just triggering the event will actually make it redraw in electron. If it doesn't, then we can try just actually changing the size and changing it back.

**Comment by gourdcaptain** [comment]
Downloaded the force-resize tree and tried it. Didn't work at all, still had the same missing window part bug. Luckily/unluckily, it's not going to affect me too much as Discord via the wrapper is too slow to be especially viable on this netbook. (Not blaming it on this project, its just running a web app vs native code. Kinda funny because friends are switching to Discord on Windows due to the less CPU useage than Skype...)

**Comment by jacobmischka** [comment]
Can you try it again? This should work now. https://github.com/jacobmischka/discord-linux/tree/force-resize

**Comment by gourdcaptain** [comment]
That one does work.

**Comment by jacobmischka** [comment]
Okay, @XNBlank how do you feel about using this workaround? If you want it you should accept #28 and  decline #27, otherwise vice versa.
